package logging

// Log logs the supplied message. Log level.
func Log(context, msg string, args ...interface{}) {

}

// Debug logs the supplied message. Debug level.
func Debug(context, msg string, args ...interface{}) {

}

// Info logs the supplied message. Acknowledgement level.
func Info(context, msg string, args ...interface{}) {

}

// Notice logs the supplied message. Caution level.
func Notice(context, msg string, args ...interface{}) {

}

// Warning logs the supplied message. Warning level.
func Warning(context, msg string, args ...interface{}) {

}

// Error logs the supplied message. Error report.
func Error(context, msg string, args ...interface{}) {

}

// Critical logs the supplied message. Catastrophic level.
func Critical(context, msg string, args ...interface{}) {

}

// RegisterLogObserver adds an observer to record the logs generated by kupak
func RegisterLogObserver() {

}

func log() {

}

type localLogger struct {
}
